### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
@greenrivers

**Comment by Justman10000** [comment]
@MajorKuprich

**Comment by MajorKuprich** [comment]
Hi @Justman10000,

Thanks for translations. :-)
Changes available in new release: https://github.com/greenrivers/grav-plugin-hotjar/releases/tag/1.0.1

**Comment by Justman10000** [comment]
> Hi @Justman10000,
> 
> Thanks for translations. :-) Changes available in new release: https://github.com/greenrivers/grav-plugin-hotjar/releases/tag/1.0.1

Instead of simply merging🤦

**Comment by MajorKuprich** [comment]
As You can see :-)

**Comment by Justman10000** [comment]
> As You can see :-)

I meant, you can simply merge PRs

**Comment by MajorKuprich** [comment]
I know it perfectly man.

**Comment by Justman10000** [comment]
> I know it perfectly man.

You do know where I'm talking about?

**Pull request closed without merging**
